# Build Stage
FROM node:18.12 as build
WORKDIR /app
COPY package*.json .
RUN yarn
COPY . .
RUN yarn run build

# NGINX will serve production files
FROM nginx:1.22 as production
WORKDIR /app
COPY --from=build /app/dist/ /usr/share/nginx/html
COPY --from=build /app/conf/nginx.conf /etc/nginx/conf.d/default.conf
ENTRYPOINT ["nginx", "-g", "daemon off;"]