version: "3"
services:
  frontend:
    build:
      context: ../
      dockerfile: Dockerfile.local
    network_mode: host
    env_file:
      - ../../frontend.env
    volumes:
      - ../:/app
      - /app/node_modules